[pytest]
testpaths = src/tests tests/unit
pythonpath = src
log_cli = true
log_cli_level = INFO
log_level = DEBUG
log_cli_format = [%(levelname)6s] %(relativeCreated).3f %(name)s  %(relpath)s:%(lineno)d %(funcName)s: %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
log_format = %(asctime)s [%(levelname)6s] %(relativeCreated).3f %(name)s  %(relpath)s:%(lineno)d %(funcName)s: %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
