SIDEREAL_DAY_SECONDS = 86164.0905
SIDEREAL_RATE_HOURS_PER_SECOND = 24.0 / SIDEREAL_DAY_SECONDS
SIDEREAL_RATE_DEGREES_PER_SECOND = 360.0 / SIDEREAL_DAY_SECONDS

GUIDE_RATE_MULTIPLIER = 0.5
CENTER_RATE_MULTIPLIER = 8.0
FIND_RATE_MULTIPLIER = 32.0
MAX_RATE_MULTIPLIER = 128.0

GUIDE_SPEED_BASELINE_MS = 1000.0
GUIDE_SPEED_MIN_SCALE = 0.1
GUIDE_SPEED_MAX_SCALE = 4.0

AXIS_IDLE_POLL_INTERVAL = 0.05
AXIS_GOTO_POLL_INTERVAL = 0.05
AXIS_COMMAND_TIMEOUT = 5.0

POLAR_MIN_SAMPLES = 4
POLAR_GUIDE_TIMEOUT_SECONDS = 4.0
POLAR_TAKEOVER_DELAY_SECONDS = 0.25
POLAR_TAKEOVER_MAX_SECONDS = 12.0
POLAR_MAX_POSITION_DELTA_DEGREES = 2.0
POLAR_MAX_SPEED_JUMP_DEGREES_PER_SECOND = 0.02

MONITOR_POLL_INTERVAL = 0.2
