SIDEREAL_DAY_SECONDS = 86164.0905
SIDEREAL_RATE_HOURS_PER_SECOND = 24.0 / SIDEREAL_DAY_SECONDS
SIDEREAL_RATE_DEGREES_PER_SECOND = 360.0 / SIDEREAL_DAY_SECONDS

GUIDE_RATE_MULTIPLIER = 0.5
CENTER_RATE_MULTIPLIER = 8.0
FIND_RATE_MULTIPLIER = 32.0
MAX_RATE_MULTIPLIER = 128.0

GUIDE_INTERVAL_SECONDS = 4.0

AXIS_IDLE_POLL_INTERVAL = 0.05
AXIS_GOTO_POLL_INTERVAL = 0.05
AXIS_COMMAND_TIMEOUT = 5.0

POLAR_MIN_SAMPLES = 5
POLAR_GUIDE_TIMEOUT_SECONDS = 20.0
POLAR_AXIS_STOP_AFTER_SECONDS = 4.1
POLAR_MAX_POSITION_DELTA_DEGREES = 2.0
POLAR_MAX_SPEED_JUMP_DEGREES_PER_SECOND = 0.02
POLAR_RA_SPEED_TOLERANCE_PERCENT = 5.0
POLAR_DEC_SPEED_TOLERANCE_PERCENT = 5.0

MONITOR_POLL_INTERVAL = 0.2
